# Adopted from https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
name: Publish Docker image

on:
  push:
    tags:
      - v*
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in
    # this job. This is necessary to publish the Docker image to GitHub
    # Packages.
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Uses the `docker/login-action` action to log in to the Container
      # registry using the account and password that will publish the packages.
      # Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # This step uses docker/metadata-action
      # https://github.com/docker/metadata-action#about to extract tags and
      # labels that will be applied to the specified image. The `id` "meta"
      # allows the output of this step to be referenced in a subsequent step.
      # The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

      # This step uses the `docker/build-push-action` action to build the
      # image, based on the  If the build succeeds, it pushes the image to
      # GitHub Packages. It uses the `context` parameter to define the build's
      # context as the set of files located in the specified path. It uses the
      # `tags` and `labels` parameters to tag and label the image with the
      # output from the "meta" step. For more information, see
      # https://github.com/docker/build-push-action#usage.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
